version: "3.8"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=1809
      - POSTGRES_DB=auth_service
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
